version: 2
jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: /go/src/github.com/anastasia1201/invoicer-chapter3
    docker:
      - image: circleci/golang:1.10
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/anastasia1201"' >> $BASH_ENV
      - run: echo 'export DOCKER_REPO="$(if [ anastasia1201 == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      - run:
          name: Build application container
          command: |
            go install --ldflags '-extldflags "-static"' github.com/anastasia1201/invoicer-chapter3;
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/invoicer-chapter3" bin/invoicer;
            docker build -t ${DOCKER_REPO}/invoicer-chapter3 .;
            docker network create --driver bridge secdevops-net

      - run:
          name: Run application in background
          command: |
            docker run \
                --network secdevops-net \
                --name invoicer \
                ${DOCKER_REPO}/invoicer-chapter3
          background: true

      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
            (
            docker pull owasp/zap2docker-weekly && \
            docker run \
                --network secdevops-net \
                -t owasp/zap2docker-weekly zap-baseline.py \
                -u https://raw.githubusercontent.com/anastasia1201/invoicer-chapter3/master/zap-baseline.conf \
                -t http://anastasiaapp-inv-invoicer-api.eba-kejk3wtz.us-east-1.elasticbeanstalk.com/ || \
            exit 0
            )

      - deploy:
          # Push application container to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
                echo ${DOCKER_USER}/invoicer-chapter3:${CIRCLE_TAG};
                go install --ldflags '-extldflags "-static"' github.com/anastasia1201/invoicer-chapter3;
                [ ! -e bin ] && mkdir bin;
                cp "$GOPATH_HEAD/bin/invoicer-chapter3" bin/invoicer;
                docker build -t ${DOCKER_REPO}/invoicer-chapter3 .;
                docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
                docker push ${DOCKER_REPO}/invoicer-chapter3;
            fi
            
